#!/usr/bin/sh

#  +---------------------------------------------------------------+
#  | etaoin-shrdlu: LISP interpreter for the SHRDLU project        |
#  |                                                               |
#  | Original source code is published in github resository:       |
#  | https://github.com/pcerman/etaoin-shrdlu.                     |
#  |                                                               |
#  | Copyright (c) 2021 Peter Cerman (https://github.com/pcerman)  |
#  |                                                               |
#  | This source code is released under Mozilla Public License 2.0 |
#  +---------------------------------------------------------------+


rlwrap -H .etaoin_history java -Xss10m -jar dist/etaoin.jar $*
